title: Ahmed Zaghloul
email: ahmedzaghloul@protonmail.ch
twitter_username: Ene00A
github_username: Ene00A
theme: minima
plugins:
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false  
